/**
 * guide-data.js — données partagées entre js/guide.js (diaporamas) et
 * js/etablissement.js (page de détail par adresse). Un seul endroit à
 * modifier pour ajouter/changer une adresse du guide.
 *
 * Les champs traduisibles (tag, desc, why, highlights) sont des objets
 * {fr, en, es, pt} — utiliser la fonction L() ci-dessous pour lire la
 * valeur dans la langue actuelle (repli sur le français si absente).
 * `highlights` est aussi un objet {fr,en,es,pt}, mais dont chaque valeur
 * est un tableau : L(item.highlights) renvoie directement ce tableau.
 * `img`, `name`, `venue`, `mapsQuery`, `heroPos` ne se traduisent pas.
 *
 * `venue:true` = une vraie adresse à visiter → cliquable, ouvre une page
 * de détail avec un bouton "Y aller" (recherche Google Maps par nom).
 * Les 4 entrées "Spécialité" du carrousel restaurants ne sont pas des
 * adresses mais des plats à showcaser : elles restent seulement figeables
 * au clic (comportement précédent), sans page de détail.
 */

/** Lit un champ traduisible {fr,en,es,pt} dans la langue actuelle (repli FR). */
function L(field) {
  if (field == null) return field;
  if (typeof field === 'string') return field; // déjà une chaîne simple (ex. anciennes données)
  const lang = (window.LUZDOSOL_LANG || 'fr');
  return field[lang] || field.fr || '';
}
const GUIDE_RESTAURANTS = [
  { img: 'a-001', name: 'Alfredo', venue: true,
    tag: { fr: 'En famille', en: 'Family-friendly', es: 'En familia', pt: 'Em família' },
    desc: { fr: 'Cuisine portugaise conviviale', en: 'Friendly Portuguese cuisine', es: 'Cocina portuguesa acogedora', pt: 'Cozinha portuguesa acolhedora' },
    mapsQuery: 'Alfredo Restaurante, Albufeira, Portugal',
    why: { fr: "C'est l'une des adresses où nous aimons emmener nos hôtes en famille : ambiance simple et chaleureuse, service souriant, et un cadre où les enfants sont toujours bien accueillis.",
      en: "One of the places we love taking our guests as a family: a simple, warm atmosphere, friendly service, and a setting where children are always welcome.",
      es: "Es una de las direcciones donde nos gusta llevar a nuestros huéspedes en familia: ambiente sencillo y cálido, servicio sonriente, y un lugar donde los niños siempre son bienvenidos.",
      pt: "É um dos locais que gostamos de levar os nossos hóspedes em família: ambiente simples e acolhedor, serviço simpático, e um espaço onde as crianças são sempre bem-vindas." },
    highlights: {
      fr: ['Cuisine portugaise traditionnelle, copieuse et généreuse', 'Ambiance décontractée, idéale avec des enfants', "À quelques minutes de l'appartement LUZDOSOL"],
      en: ['Traditional Portuguese cuisine, hearty and generous', 'Relaxed atmosphere, great with children', 'A few minutes from the LUZDOSOL apartment'],
      es: ['Cocina portuguesa tradicional, abundante y generosa', 'Ambiente relajado, ideal con niños', 'A pocos minutos del apartamento LUZDOSOL'],
      pt: ['Cozinha portuguesa tradicional, farta e generosa', 'Ambiente descontraído, ideal com crianças', 'A poucos minutos do apartamento LUZDOSOL'] } },
  { img: 'a-002', name: 'Jardim Rústico', venue: true,
    tag: { fr: 'En famille', en: 'Family-friendly', es: 'En familia', pt: 'Em família' },
    desc: { fr: 'Grillades en terrasse', en: 'Grilled dishes on the terrace', es: 'Parrilladas en terraza', pt: 'Grelhados em esplanada' },
    mapsQuery: 'Jardim Rustico Albufeira, Portugal',
    why: { fr: "Une terrasse agréable et des grillades généreuses : le genre d'endroit détendu où toute la famille peut passer une bonne soirée sans se presser.",
      en: "A pleasant terrace and generous grilled dishes: the kind of relaxed place where the whole family can enjoy a good evening without rushing.",
      es: "Una terraza agradable y parrilladas generosas: el tipo de lugar relajado donde toda la familia puede pasar una buena velada sin prisas.",
      pt: "Uma esplanada agradável e grelhados generosos: o tipo de lugar descontraído onde toda a família pode passar uma boa noite sem pressa." },
    highlights: {
      fr: ['Grillades au feu de bois en terrasse', 'Cadre extérieur agréable, parfait en soirée', 'Bon rapport qualité-prix pour un repas en famille'],
      en: ['Wood-fire grilled dishes on the terrace', 'Pleasant outdoor setting, perfect in the evening', 'Good value for a family meal'],
      es: ['Parrilladas a la leña en terraza', 'Ambiente exterior agradable, perfecto por la noche', 'Buena relación calidad-precio para comer en familia'],
      pt: ['Grelhados na brasa em esplanada', 'Espaço exterior agradável, perfeito à noite', 'Boa relação qualidade-preço para uma refeição em família'] } },
  { img: 'a-003', name: "Vivaldo's", venue: true,
    tag: { fr: 'En famille', en: 'Family-friendly', es: 'En familia', pt: 'Em família' },
    desc: { fr: 'Poissons et fruits de mer', en: 'Fish and seafood', es: 'Pescados y mariscos', pt: 'Peixe e marisco' },
    mapsQuery: "Vivaldo's Restaurante, Albufeira, Portugal",
    why: { fr: "Pour les amateurs de poisson frais : une adresse simple et sans chichi que nous recommandons volontiers aux familles qui aiment les produits de la mer.",
      en: "For fans of fresh fish: a simple, no-fuss place we happily recommend to families who love seafood.",
      es: "Para los amantes del pescado fresco: una dirección sencilla y sin pretensiones que recomendamos con gusto a las familias que aman los productos del mar.",
      pt: "Para os amantes de peixe fresco: um local simples e sem pretensões que recomendamos com todo o gosto às famílias que gostam de produtos do mar." },
    highlights: {
      fr: ['Poissons et fruits de mer frais', 'Portions généreuses, ambiance familiale', 'Une valeur sûre pour un dîner sans stress'],
      en: ['Fresh fish and seafood', 'Generous portions, family atmosphere', 'A safe bet for a stress-free dinner'],
      es: ['Pescado y marisco frescos', 'Raciones generosas, ambiente familiar', 'Una apuesta segura para una cena sin estrés'],
      pt: ['Peixe e marisco frescos', 'Doses generosas, ambiente familiar', 'Uma aposta segura para um jantar tranquilo'] } },
  { img: 'a-004', name: 'Al Quimia', venue: true,
    tag: { fr: 'En couple', en: 'For couples', es: 'En pareja', pt: 'A dois' },
    desc: { fr: 'Cadre romantique', en: 'Romantic setting', es: 'Ambiente romántico', pt: 'Ambiente romântico' },
    mapsQuery: 'Al Quimia Restaurante, Albufeira, Portugal',
    why: { fr: "Un cadre soigné, plus intime, que nous conseillons pour un dîner en couple ou une soirée un peu spéciale pendant votre séjour.",
      en: "A polished, more intimate setting we recommend for a dinner as a couple or a slightly special evening during your stay.",
      es: "Un lugar cuidado y más íntimo que recomendamos para una cena en pareja o una velada especial durante tu estancia.",
      pt: "Um espaço cuidado e mais íntimo que recomendamos para um jantar a dois ou uma noite especial durante a sua estadia." },
    highlights: {
      fr: ['Ambiance feutrée, idéale pour un dîner à deux', 'Présentation soignée des plats', 'Pensez à réserver en haute saison'],
      en: ['Cosy atmosphere, ideal for a dinner for two', 'Beautifully presented dishes', 'Book ahead in high season'],
      es: ['Ambiente acogedor, ideal para una cena en pareja', 'Platos con presentación cuidada', 'Reserva con antelación en temporada alta'],
      pt: ['Ambiente acolhedor, ideal para um jantar a dois', 'Pratos com apresentação cuidada', 'Reserve com antecedência na época alta'] } },
  { img: 'a-005', name: 'Olive Bistro', venue: true,
    tag: { fr: 'En couple', en: 'For couples', es: 'En pareja', pt: 'A dois' },
    desc: { fr: 'Cuisine raffinée', en: 'Refined cuisine', es: 'Cocina refinada', pt: 'Cozinha refinada' },
    mapsQuery: 'Olive Bistro Albufeira, Portugal',
    why: { fr: "Une cuisine plus raffinée, dans un cadre agréable — une belle option pour une soirée en couple loin de l'agitation de la vieille ville.",
      en: "More refined cuisine in a pleasant setting — a lovely option for an evening as a couple away from the old town's bustle.",
      es: "Una cocina más refinada, en un entorno agradable: una bonita opción para una velada en pareja lejos del bullicio del casco antiguo.",
      pt: "Uma cozinha mais refinada, num ambiente agradável — uma bela opção para uma noite a dois longe da agitação da zona histórica." },
    highlights: {
      fr: ['Cuisine travaillée, cadre élégant', 'Bon choix pour une occasion particulière', 'Ambiance calme, service attentionné'],
      en: ['Elaborate cuisine, elegant setting', 'A good choice for a special occasion', 'Calm atmosphere, attentive service'],
      es: ['Cocina elaborada, entorno elegante', 'Buena opción para una ocasión especial', 'Ambiente tranquilo, servicio atento'],
      pt: ['Cozinha elaborada, espaço elegante', 'Boa escolha para uma ocasião especial', 'Ambiente calmo, serviço atencioso'] } },
  { img: 'a-006', name: 'Staar Restaurante', venue: true,
    tag: { fr: 'En couple', en: 'For couples', es: 'En pareja', pt: 'A dois' },
    desc: { fr: "Soirée d'exception", en: 'A special evening', es: 'Una velada especial', pt: 'Uma noite especial' },
    mapsQuery: 'Staar Restaurante, Albufeira, Portugal',
    why: { fr: "Pour marquer un moment particulier de votre séjour : cadre soigné et ambiance plus chic, parfait pour une soirée en couple.",
      en: "To mark a special moment of your stay: a polished setting and a chicer atmosphere, perfect for an evening as a couple.",
      es: "Para celebrar un momento especial de tu estancia: un entorno cuidado y un ambiente más elegante, perfecto para una velada en pareja.",
      pt: "Para assinalar um momento especial da sua estadia: um espaço cuidado e um ambiente mais chique, perfeito para uma noite a dois." },
    highlights: {
      fr: ['Cadre soigné pour une occasion spéciale', 'Carte variée, bon accompagnement de vins', 'Réservation conseillée'],
      en: ['Polished setting for a special occasion', 'Varied menu, good wine pairing', 'Booking recommended'],
      es: ['Entorno cuidado para una ocasión especial', 'Carta variada, buen maridaje de vinos', 'Se recomienda reservar'],
      pt: ['Espaço cuidado para uma ocasião especial', 'Carta variada, bom acompanhamento de vinhos', 'Reserva recomendada'] } },
  { img: 'a-007', name: "D'VOLTA Vinhos & Tapas", venue: true,
    tag: { fr: 'Entre amis', en: 'With friends', es: 'Entre amigos', pt: 'Entre amigos' },
    desc: { fr: 'Vins et petits plats à partager', en: 'Wine and dishes to share', es: 'Vinos y platos para compartir', pt: 'Vinhos e petiscos para partilhar' },
    mapsQuery: "D'Volta Vinhos e Tapas, Albufeira, Portugal",
    why: { fr: "Idéal entre amis : petits plats à partager, bonne sélection de vins portugais, ambiance conviviale qui se prête bien aux longues soirées.",
      en: "Ideal with friends: small dishes to share, a good selection of Portuguese wines, a friendly vibe perfect for long evenings.",
      es: "Ideal entre amigos: platos pequeños para compartir, buena selección de vinos portugueses, ambiente cercano perfecto para veladas largas.",
      pt: "Ideal entre amigos: petiscos para partilhar, boa seleção de vinhos portugueses, ambiente convivial perfeito para noites longas." },
    highlights: {
      fr: ['Petits plats à partager, format tapas', 'Belle carte de vins portugais', 'Ambiance animée, parfait entre amis'],
      en: ['Tapas-style dishes to share', 'Great Portuguese wine list', 'Lively atmosphere, perfect with friends'],
      es: ['Platos para compartir estilo tapas', 'Buena carta de vinos portugueses', 'Ambiente animado, perfecto entre amigos'],
      pt: ['Petiscos para partilhar, formato tapas', 'Boa carta de vinhos portugueses', 'Ambiente animado, perfeito entre amigos'] } },
  { img: 'a-008', name: 'Copos & Petiscos', venue: true,
    tag: { fr: 'Entre amis', en: 'With friends', es: 'Entre amigos', pt: 'Entre amigos' },
    desc: { fr: 'Ambiance conviviale', en: 'Friendly atmosphere', es: 'Ambiente cercano', pt: 'Ambiente convivial' },
    mapsQuery: 'Copos e Petiscos, Albufeira, Portugal',
    why: { fr: "Une adresse simple et animée pour un apéro ou un dîner décontracté entre amis, avec de bons petiscos à partager.",
      en: "A simple, lively spot for drinks or a casual dinner with friends, with good petiscos to share.",
      es: "Una dirección sencilla y animada para tomar algo o cenar de forma relajada entre amigos, con buenos petiscos para compartir.",
      pt: "Um local simples e animado para um copo ou um jantar descontraído entre amigos, com bons petiscos para partilhar." },
    highlights: {
      fr: ['Petiscos variés à partager', 'Ambiance conviviale et détendue', 'Bon rapport qualité-prix'],
      en: ['Varied petiscos to share', 'Friendly, relaxed atmosphere', 'Good value for money'],
      es: ['Petiscos variados para compartir', 'Ambiente cercano y relajado', 'Buena relación calidad-precio'],
      pt: ['Petiscos variados para partilhar', 'Ambiente convivial e descontraído', 'Boa relação qualidade-preço'] } },
  { img: 'a-009', name: 'Stews & More', venue: true,
    tag: { fr: 'Entre amis', en: 'With friends', es: 'Entre amigos', pt: 'Entre amigos' },
    desc: { fr: 'Tapas et bonne humeur', en: 'Tapas and good vibes', es: 'Tapas y buen ambiente', pt: 'Petiscos e boa disposição' },
    mapsQuery: 'Stews and More Albufeira, Portugal',
    why: { fr: "Bonne humeur garantie : une adresse simple, sans prétention, où on partage volontiers plusieurs plats en grande tablée.",
      en: "Good vibes guaranteed: a simple, unpretentious place where sharing several dishes around a big table feels natural.",
      es: "Buen ambiente garantizado: una dirección sencilla y sin pretensiones donde apetece compartir varios platos en una gran mesa.",
      pt: "Boa disposição garantida: um local simples e sem pretensões onde apetece partilhar vários pratos numa grande mesa." },
    highlights: {
      fr: ['Formule tapas conviviale', 'Ambiance chaleureuse, service souriant', 'Pratique pour un groupe'],
      en: ['Friendly tapas-style menu', 'Warm atmosphere, cheerful service', 'Convenient for groups'],
      es: ['Formato tapas para compartir', 'Ambiente cálido, servicio sonriente', 'Práctico para grupos'],
      pt: ['Formato de petiscos para partilhar', 'Ambiente caloroso, serviço simpático', 'Prático para grupos'] } },
  { img: 'a-042', name: 'Cataplana', venue: false,
    tag: { fr: 'Spécialité', en: 'Speciality', es: 'Especialidad', pt: 'Especialidade' },
    desc: { fr: 'Ragoût de fruits de mer', en: 'Seafood stew', es: 'Guiso de marisco', pt: 'Ensopado de marisco' } },
  { img: 'a-043', name: 'Polvo à Lagareiro', venue: false,
    tag: { fr: 'Spécialité', en: 'Speciality', es: 'Especialidad', pt: 'Especialidade' },
    desc: { fr: "Poulpe grillé à l'huile d'olive", en: 'Octopus grilled in olive oil', es: 'Pulpo a la plancha con aceite de oliva', pt: 'Polvo grelhado com azeite' } },
  { img: 'a-044', name: 'Bacalhau à Brás', venue: false,
    tag: { fr: 'Spécialité', en: 'Speciality', es: 'Especialidad', pt: 'Especialidade' },
    desc: { fr: 'Morue effilochée', en: 'Shredded salt cod', es: 'Bacalao desmenuzado', pt: 'Bacalhau desfiado' } },
  { img: 'a-045', name: 'Pastel de Nata', venue: false,
    tag: { fr: 'Spécialité', en: 'Speciality', es: 'Especialidad', pt: 'Especialidade' },
    desc: { fr: 'Le célèbre flan pâtissier portugais', en: 'The famous Portuguese custard tart', es: 'El famoso pastel de nata portugués', pt: 'O famoso pastel de nata português' } },
];

// Crédits photo (licence Creative Commons — Wikimedia Commons), requis par la
// licence pour les photos CC BY / CC BY-SA. Affichés en petit sous la galerie
// de spécialités et, quand pertinent, sous la fiche d'une adresse.
const GUIDE_DISH_CREDITS = [
  { file: 'a-042', credit: 'Cataplana — photo © Wikimedia Commons contributor, CC BY-SA 4.0' },
  { file: 'a-043', credit: 'Grilled octopus — photo © Iannis Karakatsanes, CC BY-SA 2.0' },
  { file: 'a-044', credit: 'Bacalhau à Brás — photo © Fpenteado, CC BY-SA 3.0' },
  { file: 'a-045', credit: 'Pastéis de Nata — photo © helmut.weigel, CC BY-SA 4.0' },
];
const GUIDE_PHOTO_CREDITS = {
  'a-046': 'Praia dos Pescadores, Albufeira — photo © Planax (domaine public)',
  'a-047': 'Ponta da Piedade, Lagos — photo © Jose A., CC BY 2.0',
  'a-048': 'Praia da Rocha, Portimão — photo © Jose A., CC BY 2.0',
};

const GUIDE_SUPER = ['a-014a', 'a-014b', 'a-014c', 'a-014d'];

const GUIDE_NOCTURNE = [
  { img: 'a-018', name: 'Sal Rosa', venue: true,
    tag: { fr: 'Bar à cocktails', en: 'Cocktail bar', es: 'Bar de cócteles', pt: 'Bar de cocktails' },
    desc: { fr: 'Cocktails signatures et terrasse', en: 'Signature cocktails and terrace', es: 'Cócteles de autor y terraza', pt: 'Cocktails de autor e esplanada' },
    mapsQuery: 'Sal Rosa Albufeira, Portugal',
    why: { fr: "Une terrasse agréable pour commencer la soirée en douceur, avec de bons cocktails et une ambiance décontractée.",
      en: "A pleasant terrace to ease into the evening, with good cocktails and a relaxed atmosphere.",
      es: "Una terraza agradable para empezar la noche con calma, con buenos cócteles y ambiente relajado.",
      pt: "Uma esplanada agradável para começar a noite com calma, com bons cocktails e ambiente descontraído." },
    highlights: { fr: ['Cocktails signatures', 'Terrasse agréable en soirée', 'Bonne étape avant le dîner'],
      en: ['Signature cocktails', 'Pleasant evening terrace', 'A good stop before dinner'],
      es: ['Cócteles de autor', 'Terraza agradable por la noche', 'Buena parada antes de cenar'],
      pt: ['Cocktails de autor', 'Esplanada agradável ao anoitecer', 'Boa paragem antes do jantar'] } },
  { img: 'a-019', name: 'Tonic Bar', venue: true,
    tag: { fr: 'Bar à cocktails', en: 'Cocktail bar', es: 'Bar de cócteles', pt: 'Bar de cocktails' },
    desc: { fr: 'Cocktails artisanaux', en: 'Craft cocktails', es: 'Cócteles artesanales', pt: 'Cocktails artesanais' },
    mapsQuery: 'Tonic Bar Albufeira, Portugal',
    why: { fr: "Des cocktails soignés dans une ambiance plus intimiste — une bonne option pour démarrer la soirée entre amis ou en couple.",
      en: "Well-crafted cocktails in a more intimate setting — a good option to kick off the evening with friends or as a couple.",
      es: "Cócteles cuidados en un ambiente más íntimo: una buena opción para empezar la noche entre amigos o en pareja.",
      pt: "Cocktails cuidados num ambiente mais íntimo — uma boa opção para começar a noite entre amigos ou a dois." },
    highlights: { fr: ['Cocktails artisanaux', 'Ambiance cosy', 'Idéal en petit groupe'],
      en: ['Craft cocktails', 'Cosy atmosphere', 'Great for a small group'],
      es: ['Cócteles artesanales', 'Ambiente acogedor', 'Ideal en grupo reducido'],
      pt: ['Cocktails artesanais', 'Ambiente aconchegante', 'Ideal em grupo pequeno'] } },
  { img: 'a-020', name: 'Yolo Treehouse', venue: true,
    tag: { fr: 'Bar à cocktails', en: 'Cocktail bar', es: 'Bar de cócteles', pt: 'Bar de cocktails' },
    desc: { fr: 'Rooftop tropical, ambiance chic', en: 'Tropical rooftop, chic vibe', es: 'Rooftop tropical, ambiente chic', pt: 'Rooftop tropical, ambiente chique' },
    mapsQuery: 'Yolo Treehouse Albufeira, Portugal',
    why: { fr: "Un rooftop à l'ambiance tropicale et soignée, parfait pour admirer le coucher de soleil avant de poursuivre la soirée.",
      en: "A rooftop with a polished tropical vibe, perfect for watching the sunset before continuing the evening.",
      es: "Un rooftop de ambiente tropical y cuidado, perfecto para ver el atardecer antes de seguir la noche.",
      pt: "Um rooftop de ambiente tropical e cuidado, perfeito para admirar o pôr do sol antes de continuar a noite." },
    highlights: { fr: ['Rooftop avec vue', 'Ambiance chic et tropicale', 'Parfait pour le coucher de soleil'],
      en: ['Rooftop with a view', 'Chic, tropical atmosphere', 'Perfect for sunset'],
      es: ['Rooftop con vistas', 'Ambiente chic y tropical', 'Perfecto para el atardecer'],
      pt: ['Rooftop com vista', 'Ambiente chique e tropical', 'Perfeito para o pôr do sol'] } },
  { img: 'a-021', name: 'Paulos Bar', venue: true,
    tag: { fr: 'Bar animé', en: 'Lively bar', es: 'Bar animado', pt: 'Bar animado' },
    desc: { fr: 'Musique live', en: 'Live music', es: 'Música en vivo', pt: 'Música ao vivo' },
    mapsQuery: 'Paulos Bar Albufeira, Portugal',
    why: { fr: "De la musique live et une ambiance animée — une bonne adresse pour une soirée festive dans la vieille ville.",
      en: "Live music and a lively atmosphere — a good spot for a festive evening in the old town.",
      es: "Música en vivo y ambiente animado: una buena dirección para una noche festiva en el casco antiguo.",
      pt: "Música ao vivo e ambiente animado — um bom local para uma noite festiva na zona histórica." },
    highlights: { fr: ['Musique live régulière', 'Ambiance animée', 'Au cœur de la vieille ville'],
      en: ['Regular live music', 'Lively atmosphere', 'In the heart of the old town'],
      es: ['Música en vivo habitual', 'Ambiente animado', 'En pleno casco antiguo'],
      pt: ['Música ao vivo regular', 'Ambiente animado', 'No coração da zona histórica'] } },
  { img: 'a-022', name: 'Hot Sun Bar', venue: true,
    tag: { fr: 'Bar animé', en: 'Lively bar', es: 'Bar animado', pt: 'Bar animado' },
    desc: { fr: 'Happy hour et soirées festives', en: 'Happy hour and festive nights', es: 'Happy hour y noches festivas', pt: 'Happy hour e noites festivas' },
    mapsQuery: 'Hot Sun Bar Albufeira, Portugal',
    why: { fr: "Happy hour et ambiance festive : l'endroit où beaucoup de nos hôtes aiment démarrer leur soirée entre amis.",
      en: "Happy hour and a festive vibe: the spot many of our guests like to start their evening with friends.",
      es: "Happy hour y ambiente festivo: el lugar donde muchos de nuestros huéspedes empiezan la noche entre amigos.",
      pt: "Happy hour e ambiente festivo: o local onde muitos dos nossos hóspedes gostam de começar a noite entre amigos." },
    highlights: { fr: ['Happy hour', 'Ambiance festive', 'Bon plan avant de sortir'],
      en: ['Happy hour', 'Festive atmosphere', 'A good stop before going out'],
      es: ['Happy hour', 'Ambiente festivo', 'Buen plan antes de salir'],
      pt: ['Happy hour', 'Ambiente festivo', 'Boa paragem antes de sair'] } },
  { img: 'a-023', name: 'Portas da Villa', venue: true,
    tag: { fr: 'Bar animé', en: 'Lively bar', es: 'Bar animado', pt: 'Bar animado' },
    desc: { fr: 'Bar convivial de la vieille ville', en: 'Friendly old-town bar', es: 'Bar cercano del casco antiguo', pt: 'Bar convivial da zona histórica' },
    mapsQuery: 'Portas da Vila Albufeira, Portugal',
    why: { fr: "Un bar convivial en plein cœur de la vieille ville, pratique pour un verre avant d'aller danser.",
      en: "A friendly bar right in the heart of the old town, handy for a drink before heading out dancing.",
      es: "Un bar cercano en pleno casco antiguo, práctico para tomar algo antes de ir a bailar.",
      pt: "Um bar convivial no coração da zona histórica, prático para um copo antes de ir dançar." },
    highlights: { fr: ['Emplacement central', 'Ambiance conviviale', 'Bon point de départ de soirée'],
      en: ['Central location', 'Friendly atmosphere', 'A good starting point for the evening'],
      es: ['Ubicación céntrica', 'Ambiente cercano', 'Buen punto de partida para la noche'],
      pt: ['Localização central', 'Ambiente convivial', 'Bom ponto de partida para a noite'] } },
  { img: 'a-024', name: 'Kiss Disco Club', venue: true,
    tag: { fr: 'Discothèque', en: 'Nightclub', es: 'Discoteca', pt: 'Discoteca' },
    desc: { fr: 'DJ internationaux', en: 'International DJs', es: 'DJs internacionales', pt: 'DJs internacionais' },
    mapsQuery: 'Kiss Disco Club Albufeira, Portugal',
    why: { fr: "Une des discothèques les plus connues de la vieille ville, avec une programmation de DJ internationaux.",
      en: "One of the best-known clubs in the old town, with a line-up of international DJs.",
      es: "Una de las discotecas más conocidas del casco antiguo, con programación de DJs internacionales.",
      pt: "Uma das discotecas mais conhecidas da zona histórica, com programação de DJs internacionais." },
    highlights: { fr: ['DJ internationaux', 'Grande piste de danse', "Ouvre tard, ambiance jusqu'au bout de la nuit"],
      en: ['International DJs', 'Large dance floor', 'Open late, going strong all night'],
      es: ['DJs internacionales', 'Amplia pista de baile', 'Abre hasta tarde, ambiente toda la noche'],
      pt: ['DJs internacionais', 'Grande pista de dança', 'Abre até tarde, ambiente a noite toda'] } },
  { img: 'a-025', name: 'Club Spaces', venue: true,
    tag: { fr: 'Discothèque', en: 'Nightclub', es: 'Discoteca', pt: 'Discoteca' },
    desc: { fr: 'Musique électronique', en: 'Electronic music', es: 'Música electrónica', pt: 'Música eletrónica' },
    mapsQuery: 'Club Spaces Albufeira, Portugal',
    why: { fr: "Pour les amateurs de musique électronique, une salle réputée pour ses soirées jusqu'au bout de la nuit.",
      en: "For electronic music fans, a venue known for its all-night parties.",
      es: "Para los amantes de la música electrónica, una sala conocida por sus fiestas hasta el amanecer.",
      pt: "Para os amantes de música eletrónica, uma sala conhecida pelas suas festas até de madrugada." },
    highlights: { fr: ['Musique électronique', 'Ambiance clubbing', 'Plutôt pour les noctambules'],
      en: ['Electronic music', 'Club atmosphere', 'Best for night owls'],
      es: ['Música electrónica', 'Ambiente de club', 'Para los más noctámbulos'],
      pt: ['Música eletrónica', 'Ambiente de clubbing', 'Mais para os noctívagos'] } },
  { img: 'a-026', name: 'Libertos Club', venue: true,
    tag: { fr: 'Discothèque', en: 'Nightclub', es: 'Discoteca', pt: 'Discoteca' },
    desc: { fr: 'Ambiance festive', en: 'Festive atmosphere', es: 'Ambiente festivo', pt: 'Ambiente festivo' },
    mapsQuery: 'Libertos Club Albufeira, Portugal',
    why: { fr: "Une valeur sûre de la vie nocturne locale pour une soirée festive entre amis.",
      en: "A local nightlife staple for a festive evening with friends.",
      es: "Un clásico de la vida nocturna local para una noche festiva entre amigos.",
      pt: "Um valor seguro da vida noturna local para uma noite festiva entre amigos." },
    highlights: { fr: ['Ambiance festive', "Fréquenté par les groupes d'amis", 'Musique variée'],
      en: ['Festive atmosphere', 'Popular with groups of friends', 'Varied music'],
      es: ['Ambiente festivo', 'Frecuentado por grupos de amigos', 'Música variada'],
      pt: ['Ambiente festivo', 'Frequentado por grupos de amigos', 'Música variada'] } },
  { img: 'a-027', name: 'Illuzziun Club', venue: true,
    tag: { fr: 'Discothèque', en: 'Nightclub', es: 'Discoteca', pt: 'Discoteca' },
    desc: { fr: 'Tables VIP et DJ sets', en: 'VIP tables and DJ sets', es: 'Mesas VIP y sesiones de DJ', pt: 'Mesas VIP e sets de DJ' },
    mapsQuery: 'Illuzziun Club Albufeira, Portugal',
    why: { fr: "Pour une soirée un peu plus premium, avec tables VIP disponibles et de bons DJ sets.",
      en: "For a slightly more premium night out, with VIP tables available and good DJ sets.",
      es: "Para una noche algo más premium, con mesas VIP disponibles y buenas sesiones de DJ.",
      pt: "Para uma noite um pouco mais premium, com mesas VIP disponíveis e bons sets de DJ." },
    highlights: { fr: ['Tables VIP disponibles', 'DJ sets', 'Ambiance plus premium'],
      en: ['VIP tables available', 'DJ sets', 'More premium atmosphere'],
      es: ['Mesas VIP disponibles', 'Sesiones de DJ', 'Ambiente más premium'],
      pt: ['Mesas VIP disponíveis', 'Sets de DJ', 'Ambiente mais premium'] } },
  { img: 'a-028', name: 'Marina de Vilamoura', venue: true,
    tag: { fr: 'Vilamoura', en: 'Vilamoura', es: 'Vilamoura', pt: 'Vilamoura' },
    desc: { fr: 'Promenade parmi les yachts, restaurants et bars lounge', en: 'A stroll among yachts, restaurants and lounge bars', es: 'Paseo entre yates, restaurantes y bares lounge', pt: 'Passeio entre iates, restaurantes e bares lounge' },
    mapsQuery: 'Marina de Vilamoura, Portugal',
    why: { fr: "Une promenade incontournable en soirée : yachts, restaurants et bars lounge, à environ 15 minutes de l'appartement.",
      en: "A must-do evening stroll: yachts, restaurants and lounge bars, about 15 minutes from the apartment.",
      es: "Un paseo imprescindible por la noche: yates, restaurantes y bares lounge, a unos 15 minutos del apartamento.",
      pt: "Um passeio imperdível ao final do dia: iates, restaurantes e bares lounge, a cerca de 15 minutos do apartamento." },
    highlights: { fr: ["Promenade au bord de l'eau", 'Restaurants et bars lounge', 'Ambiance chic, parfait pour un apéro'],
      en: ['Waterfront promenade', 'Restaurants and lounge bars', 'Chic vibe, perfect for a drink'],
      es: ['Paseo junto al mar', 'Restaurantes y bares lounge', 'Ambiente chic, perfecto para tomar algo'],
      pt: ['Passeio à beira-mar', 'Restaurantes e bares lounge', 'Ambiente chique, perfeito para um copo'] } },
  { img: 'a-029', name: 'Casino Vilamoura', venue: true,
    tag: { fr: 'Casino', en: 'Casino', es: 'Casino', pt: 'Casino' },
    desc: { fr: 'Machines à sous, roulette, blackjack, poker — tenue correcte recommandée', en: 'Slot machines, roulette, blackjack, poker — smart dress recommended', es: 'Tragaperras, ruleta, blackjack, póker — se recomienda vestimenta adecuada', pt: 'Slots, roleta, blackjack, póquer — recomenda-se traje adequado' },
    mapsQuery: 'Casino Vilamoura, Portugal',
    why: { fr: "Pour une soirée différente : machines à sous, tables de jeu et parfois des spectacles — tenue correcte recommandée.",
      en: "For a different kind of evening: slot machines, gaming tables and sometimes shows — smart dress recommended.",
      es: "Para una noche diferente: tragaperras, mesas de juego y a veces espectáculos — se recomienda vestimenta adecuada.",
      pt: "Para uma noite diferente: slots, mesas de jogo e por vezes espetáculos — recomenda-se traje adequado." },
    highlights: { fr: ['Roulette, blackjack, poker, machines à sous', 'Tenue correcte recommandée', 'Souvent des spectacles ou concerts'],
      en: ['Roulette, blackjack, poker, slot machines', 'Smart dress recommended', 'Often live shows or concerts'],
      es: ['Ruleta, blackjack, póker, tragaperras', 'Se recomienda vestimenta adecuada', 'A menudo espectáculos o conciertos'],
      pt: ['Roleta, blackjack, póquer, slots', 'Traje adequado recomendado', 'Frequentemente espetáculos ou concertos'] } },
  { img: 'a-030', name: 'NoSoloÁgua', venue: true,
    tag: { fr: 'Beach club', en: 'Beach club', es: 'Beach club', pt: 'Beach club' },
    desc: { fr: 'Albufeira', en: 'Albufeira', es: 'Albufeira', pt: 'Albufeira' },
    mapsQuery: 'NoSoloAgua Albufeira, Portugal',
    why: { fr: "Un beach club agréable de jour comme de soir, pratique pour prolonger la journée plage en douceur.",
      en: "A pleasant beach club by day or night, handy for extending a beach day gently into the evening.",
      es: "Un beach club agradable de día y de noche, práctico para alargar el día de playa con calma.",
      pt: "Um beach club agradável de dia e de noite, prático para prolongar o dia de praia com calma." },
    highlights: { fr: ['Ambiance beach club', 'Agréable de jour comme en soirée', "Proche des plages d'Albufeira"],
      en: ['Beach club vibe', 'Great by day or evening', "Close to Albufeira's beaches"],
      es: ['Ambiente beach club', 'Agradable de día y de noche', 'Cerca de las playas de Albufeira'],
      pt: ['Ambiente beach club', 'Agradável de dia e à noite', 'Perto das praias de Albufeira'] } },
  { img: 'a-031', name: 'Purobeach', venue: true,
    tag: { fr: 'Beach club', en: 'Beach club', es: 'Beach club', pt: 'Beach club' },
    desc: { fr: 'Vilamoura', en: 'Vilamoura', es: 'Vilamoura', pt: 'Vilamoura' },
    mapsQuery: 'Purobeach Vilamoura, Portugal',
    why: { fr: "Un beach club plus haut de gamme à Vilamoura, très agréable pour une journée détente qui se prolonge en soirée.",
      en: "A more upscale beach club in Vilamoura, lovely for a relaxed day that stretches into the evening.",
      es: "Un beach club más exclusivo en Vilamoura, muy agradable para un día de relax que se alarga hasta la noche.",
      pt: "Um beach club mais requintado em Vilamoura, muito agradável para um dia de relax que se prolonga pela noite." },
    highlights: { fr: ['Ambiance premium', 'Transats et restauration sur place', 'Belle option pour une journée complète'],
      en: ['Premium atmosphere', 'Sun loungers and dining on site', 'A great option for a full day out'],
      es: ['Ambiente premium', 'Tumbonas y restauración en el lugar', 'Buena opción para un día completo'],
      pt: ['Ambiente premium', 'Espreguiçadeiras e restauração no local', 'Boa opção para um dia completo'] } },
  { img: 'a-031a', name: 'Purobeach', venue: true,
    tag: { fr: 'Beach club', en: 'Beach club', es: 'Beach club', pt: 'Beach club' },
    desc: { fr: 'Vilamoura, vue de nuit', en: 'Vilamoura, by night', es: 'Vilamoura, de noche', pt: 'Vilamoura, à noite' },
    mapsQuery: 'Purobeach Vilamoura, Portugal',
    why: { fr: "Le même Purobeach, mais de nuit : lumières et ambiance lounge pour prolonger la soirée face à la mer.",
      en: "The same Purobeach, by night: lights and a lounge vibe to extend the evening facing the sea.",
      es: "El mismo Purobeach, pero de noche: luces y ambiente lounge para prolongar la velada frente al mar.",
      pt: "O mesmo Purobeach, mas à noite: luzes e ambiente lounge para prolongar a noite em frente ao mar." },
    highlights: { fr: ['Ambiance lounge en soirée', 'Vue sur mer', 'Belle option après le dîner'],
      en: ['Evening lounge vibe', 'Sea view', 'A great option after dinner'],
      es: ['Ambiente lounge nocturno', 'Vistas al mar', 'Buena opción después de cenar'],
      pt: ['Ambiente lounge à noite', 'Vista para o mar', 'Boa opção depois do jantar'] } },
  { img: 'a-032', name: 'Heaven Beach Club', venue: true,
    tag: { fr: 'Beach club', en: 'Beach club', es: 'Beach club', pt: 'Beach club' },
    desc: { fr: 'Ambiance premium, jour et soir', en: 'Premium vibe, day and night', es: 'Ambiente premium, día y noche', pt: 'Ambiente premium, dia e noite' },
    mapsQuery: 'Heaven Beach Club Albufeira, Portugal',
    why: { fr: "Une ambiance premium toute la journée, qui se prolonge agréablement en soirée — une de nos adresses préférées près des plages.",
      en: "A premium vibe all day long that extends nicely into the evening — one of our favourite spots near the beaches.",
      es: "Un ambiente premium durante todo el día, que se prolonga agradablemente por la noche: una de nuestras direcciones favoritas cerca de las playas.",
      pt: "Um ambiente premium durante todo o dia, que se prolonga agradavelmente pela noite — um dos nossos locais preferidos perto das praias." },
    highlights: { fr: ['Ambiance premium', 'Agréable de jour comme en soirée', "Proche des plages d'Albufeira"],
      en: ['Premium atmosphere', 'Great by day or evening', "Close to Albufeira's beaches"],
      es: ['Ambiente premium', 'Agradable de día y de noche', 'Cerca de las playas de Albufeira'],
      pt: ['Ambiente premium', 'Agradável de dia e à noite', 'Perto das praias de Albufeira'] } },
];

const GUIDE_VILLES = [
  { img: 'a-033', name: 'Aéroport de Faro', venue: true,
    tag: { fr: '38 km · 35-40 min', en: '38 km · 35-40 min', es: '38 km · 35-40 min', pt: '38 km · 35-40 min' },
    desc: { fr: 'Location de voiture fortement recommandée. Taxi 45-60 € · Uber/Bolt 25-40 € · Bus économique mais plus long.',
      en: 'Renting a car is strongly recommended. Taxi €45-60 · Uber/Bolt €25-40 · Bus is cheaper but slower.',
      es: 'Se recomienda encarecidamente alquilar un coche. Taxi 45-60 € · Uber/Bolt 25-40 € · Autobús económico pero más lento.',
      pt: 'Recomenda-se vivamente o aluguer de um carro. Táxi 45-60 € · Uber/Bolt 25-40 € · Autocarro económico mas mais demorado.' },
    mapsQuery: 'Aeroporto de Faro, Portugal',
    why: { fr: "Votre point d'arrivée en Algarve. Pour la suite du séjour, une voiture de location facilite grandement les déplacements.",
      en: "Your arrival point in the Algarve. For the rest of your stay, a rental car makes getting around much easier.",
      es: "Tu punto de llegada al Algarve. Para el resto de la estancia, un coche de alquiler facilita mucho los desplazamientos.",
      pt: "O seu ponto de chegada ao Algarve. Para o resto da estadia, um carro alugado facilita muito as deslocações." },
    highlights: { fr: ['Location de voiture fortement recommandée', 'Taxi : environ 45-60 €', 'Uber/Bolt : environ 25-40 €'],
      en: ['Car rental strongly recommended', 'Taxi: about €45-60', 'Uber/Bolt: about €25-40'],
      es: ['Se recomienda encarecidamente alquilar coche', 'Taxi: unos 45-60 €', 'Uber/Bolt: unos 25-40 €'],
      pt: ['Aluguer de carro fortemente recomendado', 'Táxi: cerca de 45-60 €', 'Uber/Bolt: cerca de 25-40 €'] } },
  { img: 'a-046', name: 'Albufeira', venue: true,
    tag: { fr: '3 km · 8-10 min', en: '3 km · 8-10 min', es: '3 km · 8-10 min', pt: '3 km · 8-10 min' },
    desc: { fr: 'Vieille ville, marina, plages, excursions en bateau, restaurants et vie nocturne.',
      en: 'Old town, marina, beaches, boat trips, restaurants and nightlife.',
      es: 'Casco antiguo, puerto deportivo, playas, excursiones en barco, restaurantes y vida nocturna.',
      pt: 'Zona histórica, marina, praias, passeios de barco, restaurantes e vida noturna.' },
    mapsQuery: 'Albufeira, Portugal',
    why: { fr: "Le cœur de votre séjour : à quelques minutes de l'appartement, entre vieille ville, marina et plages.",
      en: "The heart of your stay: a few minutes from the apartment, between the old town, marina and beaches.",
      es: "El corazón de tu estancia: a pocos minutos del apartamento, entre el casco antiguo, el puerto y las playas.",
      pt: "O coração da sua estadia: a poucos minutos do apartamento, entre a zona histórica, a marina e as praias." },
    highlights: { fr: ['Vieille ville pittoresque', 'Marina et excursions en bateau', 'Plages, restaurants et vie nocturne'],
      en: ['Picturesque old town', 'Marina and boat trips', 'Beaches, restaurants and nightlife'],
      es: ['Casco antiguo pintoresco', 'Puerto deportivo y excursiones en barco', 'Playas, restaurantes y vida nocturna'],
      pt: ['Zona histórica pitoresca', 'Marina e passeios de barco', 'Praias, restaurantes e vida noturna'] } },
  { img: 'a-035', name: 'Vilamoura', venue: true,
    tag: { fr: '15 km · 20 min', en: '15 km · 20 min', es: '15 km · 20 min', pt: '15 km · 20 min' },
    desc: { fr: 'Marina de luxe, casino, golf, restaurants gastronomiques et bars lounge.',
      en: 'Luxury marina, casino, golf, fine-dining restaurants and lounge bars.',
      es: 'Puerto deportivo de lujo, casino, golf, restaurantes gastronómicos y bares lounge.',
      pt: 'Marina de luxo, casino, golfe, restaurantes gastronómicos e bares lounge.' },
    mapsQuery: 'Vilamoura, Portugal',
    why: { fr: "Une ambiance plus chic, à 20 minutes de l'appartement : idéale pour une soirée ou une journée différente.",
      en: "A chicer atmosphere, 20 minutes from the apartment: ideal for a different kind of evening or day out.",
      es: "Un ambiente más elegante, a 20 minutos del apartamento: ideal para una noche o un día diferente.",
      pt: "Um ambiente mais chique, a 20 minutos do apartamento: ideal para uma noite ou um dia diferente." },
    highlights: { fr: ['Marina de luxe', 'Casino et golf', 'Restaurants gastronomiques et bars lounge'],
      en: ['Luxury marina', 'Casino and golf', 'Fine-dining restaurants and lounge bars'],
      es: ['Puerto deportivo de lujo', 'Casino y golf', 'Restaurantes gastronómicos y bares lounge'],
      pt: ['Marina de luxo', 'Casino e golfe', 'Restaurantes gastronómicos e bares lounge'] } },
  { img: 'a-047', name: 'Lagos', venue: true,
    tag: { fr: '60 km · 50-55 min', en: '60 km · 50-55 min', es: '60 km · 50-55 min', pt: '60 km · 50-55 min' },
    desc: { fr: 'Ponta da Piedade, plages spectaculaires, grottes, kayak et centre historique.',
      en: 'Ponta da Piedade, spectacular beaches, caves, kayaking and historic centre.',
      es: 'Ponta da Piedade, playas espectaculares, cuevas, kayak y centro histórico.',
      pt: 'Ponta da Piedade, praias espetaculares, grutas, caiaque e centro histórico.' },
    mapsQuery: 'Lagos, Algarve, Portugal',
    why: { fr: "Une excursion d'une journée qui vaut vraiment le détour : falaises, grottes et plages parmi les plus belles de l'Algarve.",
      en: "A day trip that's really worth it: cliffs, caves and some of the Algarve's most beautiful beaches.",
      es: "Una excursión de un día que realmente merece la pena: acantilados, cuevas y algunas de las playas más bonitas del Algarve.",
      pt: "Uma excursão de um dia que vale mesmo a pena: falésias, grutas e algumas das praias mais bonitas do Algarve." },
    highlights: { fr: ['Ponta da Piedade et ses falaises', 'Grottes accessibles en kayak ou bateau', 'Centre historique agréable à visiter'],
      en: ['Ponta da Piedade and its cliffs', 'Caves accessible by kayak or boat', 'A pleasant historic centre to explore'],
      es: ['Ponta da Piedade y sus acantilados', 'Cuevas accesibles en kayak o barco', 'Centro histórico agradable para visitar'],
      pt: ['Ponta da Piedade e as suas falésias', 'Grutas acessíveis de caiaque ou barco', 'Centro histórico agradável para visitar'] } },
  { img: 'a-048', name: 'Portimão', venue: true,
    tag: { fr: '40 km · 35-40 min', en: '40 km · 35-40 min', es: '40 km · 35-40 min', pt: '40 km · 35-40 min' },
    desc: { fr: 'Praia da Rocha, promenade maritime, restaurants de fruits de mer et shopping.',
      en: 'Praia da Rocha, seafront promenade, seafood restaurants and shopping.',
      es: 'Praia da Rocha, paseo marítimo, restaurantes de marisco y compras.',
      pt: 'Praia da Rocha, passeio marítimo, restaurantes de marisco e compras.' },
    mapsQuery: 'Portimao, Algarve, Portugal',
    why: { fr: "Entre plage et vie urbaine : la Praia da Rocha et sa promenade sont idéales pour une journée complète.",
      en: "Between beach and city life: Praia da Rocha and its promenade are ideal for a full day out.",
      es: "Entre playa y vida urbana: la Praia da Rocha y su paseo son ideales para un día completo.",
      pt: "Entre praia e vida urbana: a Praia da Rocha e o seu passeio são ideais para um dia completo." },
    highlights: { fr: ['Praia da Rocha', 'Promenade maritime animée', 'Bons restaurants de fruits de mer'],
      en: ['Praia da Rocha', 'Lively seafront promenade', 'Good seafood restaurants'],
      es: ['Praia da Rocha', 'Animado paseo marítimo', 'Buenos restaurantes de marisco'],
      pt: ['Praia da Rocha', 'Passeio marítimo animado', 'Bons restaurantes de marisco'] } },
  { img: 'a-038', name: 'Carvoeiro', venue: true,
    tag: { fr: '30 km · 30 min', en: '30 km · 30 min', es: '30 km · 30 min', pt: '30 km · 30 min' },
    desc: { fr: "Falaises, Algar Seco, sentiers panoramiques et excursions vers les grottes marines.",
      en: "Cliffs, Algar Seco, scenic trails and boat trips to sea caves.",
      es: "Acantilados, Algar Seco, senderos panorámicos y excursiones a cuevas marinas.",
      pt: "Falésias, Algar Seco, trilhos panorâmicos e passeios até às grutas marinhas." },
    mapsQuery: 'Carvoeiro, Algarve, Portugal',
    why: { fr: "Un village de pêcheurs devenu l'une des plus belles adresses de la côte, parfait pour une balade en falaise.",
      en: "A fishing village turned into one of the coast's finest spots, perfect for a clifftop walk.",
      es: "Un pueblo de pescadores convertido en uno de los rincones más bonitos de la costa, perfecto para pasear por los acantilados.",
      pt: "Uma vila piscatória transformada num dos locais mais bonitos da costa, perfeito para um passeio pelas falésias." },
    highlights: { fr: ['Algar Seco et ses formations rocheuses', 'Sentiers panoramiques en bord de falaise', 'Excursions vers les grottes marines'],
      en: ['Algar Seco and its rock formations', 'Scenic clifftop trails', 'Boat trips to sea caves'],
      es: ['Algar Seco y sus formaciones rocosas', 'Senderos panorámicos junto al acantilado', 'Excursiones a cuevas marinas'],
      pt: ['Algar Seco e as suas formações rochosas', 'Trilhos panorâmicos junto à falésia', 'Passeios até às grutas marinhas'] } },
  { img: 'a-039', name: 'Loulé', venue: true,
    tag: { fr: '25 km · 30 min', en: '25 km · 30 min', es: '25 km · 30 min', pt: '25 km · 30 min' },
    desc: { fr: 'Marché couvert, château, artisanat et centre historique.',
      en: 'Covered market, castle, crafts and historic centre.',
      es: 'Mercado cubierto, castillo, artesanía y centro histórico.',
      pt: 'Mercado municipal, castelo, artesanato e centro histórico.' },
    mapsQuery: 'Loule, Algarve, Portugal',
    why: { fr: "Pour une ambiance plus authentique, loin du littoral : marché, artisanat local et ruelles historiques.",
      en: "For a more authentic vibe away from the coast: market, local crafts and historic lanes.",
      es: "Para un ambiente más auténtico, lejos de la costa: mercado, artesanía local y callejuelas históricas.",
      pt: "Para um ambiente mais autêntico, longe do litoral: mercado, artesanato local e ruas históricas." },
    highlights: { fr: ['Marché couvert traditionnel', 'Château et centre historique', "Bon aperçu de l'artisanat local"],
      en: ['Traditional covered market', 'Castle and historic centre', 'A good taste of local crafts'],
      es: ['Mercado cubierto tradicional', 'Castillo y centro histórico', 'Buena muestra de artesanía local'],
      pt: ['Mercado municipal tradicional', 'Castelo e centro histórico', 'Boa amostra do artesanato local'] } },
  { img: 'a-040', name: 'Tavira', venue: true,
    tag: { fr: '65 km · 55 min', en: '65 km · 55 min', es: '65 km · 55 min', pt: '65 km · 55 min' },
    desc: { fr: 'Pont romain, salines, île de Tavira et ambiance authentique.',
      en: 'Roman bridge, salt pans, Tavira Island and an authentic feel.',
      es: 'Puente romano, salinas, isla de Tavira y ambiente auténtico.',
      pt: 'Ponte romana, salinas, ilha de Tavira e ambiente autêntico.' },
    mapsQuery: 'Tavira, Algarve, Portugal',
    why: { fr: "Une des villes les plus authentiques de l'Algarve — un peu plus loin, mais qui mérite une journée complète.",
      en: "One of the most authentic towns in the Algarve — a bit further, but worth a full day.",
      es: "Una de las ciudades más auténticas del Algarve, algo más lejos, pero que merece un día completo.",
      pt: "Uma das cidades mais autênticas do Algarve — um pouco mais longe, mas que merece um dia inteiro." },
    highlights: { fr: ['Pont romain et centre historique', 'Salines et île de Tavira', 'Ambiance plus calme et authentique'],
      en: ['Roman bridge and historic centre', 'Salt pans and Tavira Island', 'Calmer, more authentic atmosphere'],
      es: ['Puente romano y centro histórico', 'Salinas e isla de Tavira', 'Ambiente más tranquilo y auténtico'],
      pt: ['Ponte romana e centro histórico', 'Salinas e ilha de Tavira', 'Ambiente mais calmo e autêntico'] } },
  { img: 'a-041', name: 'Silves', venue: true,
    tag: { fr: '30 km · 30 min', en: '30 km · 30 min', es: '30 km · 30 min', pt: '30 km · 30 min' },
    desc: { fr: 'Château médiéval, cathédrale et vieille ville.',
      en: 'Medieval castle, cathedral and old town.',
      es: 'Castillo medieval, catedral y casco antiguo.',
      pt: 'Castelo medieval, sé catedral e zona histórica.' },
    mapsQuery: 'Silves, Algarve, Portugal',
    why: { fr: "L'ancienne capitale maure de l'Algarve, avec un château médiéval impressionnant qui domine la ville.",
      en: "The Algarve's former Moorish capital, with an impressive medieval castle overlooking the town.",
      es: "La antigua capital mora del Algarve, con un impresionante castillo medieval que domina la ciudad.",
      pt: "A antiga capital moura do Algarve, com um imponente castelo medieval que domina a cidade." },
    highlights: { fr: ['Château médiéval', 'Cathédrale et vieille ville', 'Belle vue depuis les remparts'],
      en: ['Medieval castle', 'Cathedral and old town', 'Great view from the ramparts'],
      es: ['Castillo medieval', 'Catedral y casco antiguo', 'Bonitas vistas desde las murallas'],
      pt: ['Castelo medieval', 'Sé catedral e zona histórica', 'Bela vista a partir das muralhas'] } },
];
