/**
 * guide-data.js — données partagées entre js/guide.js (diaporamas) et
 * js/etablissement.js (page de détail par adresse). Un seul endroit à
 * modifier pour ajouter/changer une adresse du guide.
 *
 * `venue:true` = une vraie adresse à visiter → cliquable, ouvre une page
 * de détail avec un bouton "Y aller" (recherche Google Maps par nom).
 * Les 4 entrées "Spécialité" du carrousel restaurants ne sont pas des
 * adresses mais des plats à showcaser : elles restent seulement figeables
 * au clic (comportement précédent), sans page de détail.
 */
const GUIDE_RESTAURANTS = [
  { img: 'a-001', tag: 'En famille', name: 'Alfredo', desc: 'Cuisine portugaise conviviale', venue: true,
    mapsQuery: 'Alfredo Restaurante, Albufeira, Portugal',
    why: "C'est l'une des adresses où nous aimons emmener nos hôtes en famille : ambiance simple et chaleureuse, service souriant, et un cadre où les enfants sont toujours bien accueillis.",
    highlights: ['Cuisine portugaise traditionnelle, copieuse et généreuse', 'Ambiance décontractée, idéale avec des enfants', 'À quelques minutes de l\'appartement LUZDOSOL'] },
  { img: 'a-002', tag: 'En famille', name: 'Jardim Rústico', desc: 'Grillades en terrasse', venue: true,
    mapsQuery: 'Jardim Rustico Albufeira, Portugal',
    why: "Une terrasse agréable et des grillades généreuses : le genre d'endroit détendu où toute la famille peut passer une bonne soirée sans se presser.",
    highlights: ['Grillades au feu de bois en terrasse', 'Cadre extérieur agréable, parfait en soirée', 'Bon rapport qualité-prix pour un repas en famille'] },
  { img: 'a-003', tag: 'En famille', name: "Vivaldo's", desc: 'Poissons et fruits de mer', venue: true,
    mapsQuery: "Vivaldo's Restaurante, Albufeira, Portugal",
    why: "Pour les amateurs de poisson frais : une adresse simple et sans chichi que nous recommandons volontiers aux familles qui aiment les produits de la mer.",
    highlights: ['Poissons et fruits de mer frais', 'Portions généreuses, ambiance familiale', 'Une valeur sûre pour un dîner sans stress'] },
  { img: 'a-004', tag: 'En couple', name: 'Al Quimia', desc: 'Cadre romantique', venue: true,
    mapsQuery: 'Al Quimia Restaurante, Albufeira, Portugal',
    why: "Un cadre soigné, plus intime, que nous conseillons pour un dîner en couple ou une soirée un peu spéciale pendant votre séjour.",
    highlights: ['Ambiance feutrée, idéale pour un dîner à deux', 'Présentation soignée des plats', 'Pensez à réserver en haute saison'] },
  { img: 'a-005', tag: 'En couple', name: 'Olive Bistro', desc: 'Cuisine raffinée', venue: true,
    mapsQuery: 'Olive Bistro Albufeira, Portugal',
    why: "Une cuisine plus raffinée, dans un cadre agréable — une belle option pour une soirée en couple loin de l'agitation de la vieille ville.",
    highlights: ['Cuisine travaillée, cadre élégant', 'Bon choix pour une occasion particulière', 'Ambiance calme, service attentionné'] },
  { img: 'a-006', tag: 'En couple', name: 'Staar Restaurante', desc: "Soirée d'exception", venue: true,
    mapsQuery: 'Staar Restaurante, Albufeira, Portugal',
    why: "Pour marquer un moment particulier de votre séjour : cadre soigné et ambiance plus chic, parfait pour une soirée en couple.",
    highlights: ['Cadre soigné pour une occasion spéciale', 'Carte variée, bon accompagnement de vins', 'Réservation conseillée'] },
  { img: 'a-007', tag: 'Entre amis', name: "D'VOLTA Vinhos & Tapas", desc: 'Vins et petits plats à partager', venue: true,
    mapsQuery: "D'Volta Vinhos e Tapas, Albufeira, Portugal",
    why: "Idéal entre amis : petits plats à partager, bonne sélection de vins portugais, ambiance conviviale qui se prête bien aux longues soirées.",
    highlights: ['Petits plats à partager, format tapas', 'Belle carte de vins portugais', 'Ambiance animée, parfait entre amis'] },
  { img: 'a-008', tag: 'Entre amis', name: 'Copos & Petiscos', desc: 'Ambiance conviviale', venue: true,
    mapsQuery: 'Copos e Petiscos, Albufeira, Portugal',
    why: "Une adresse simple et animée pour un apéro ou un dîner décontracté entre amis, avec de bons petiscos à partager.",
    highlights: ['Petiscos variés à partager', 'Ambiance conviviale et détendue', 'Bon rapport qualité-prix'] },
  { img: 'a-009', tag: 'Entre amis', name: 'Stews & More', desc: 'Tapas et bonne humeur', venue: true,
    mapsQuery: 'Stews and More Albufeira, Portugal',
    why: "Bonne humeur garantie : une adresse simple, sans prétention, où on partage volontiers plusieurs plats en grande tablée.",
    highlights: ['Formule tapas conviviale', 'Ambiance chaleureuse, service souriant', 'Pratique pour un groupe'] },
  { img: 'a-010', tag: 'Spécialité', name: 'Cataplana', desc: 'Ragoût de fruits de mer', venue: false },
  { img: 'a-011', tag: 'Spécialité', name: 'Polvo à Lagareiro', desc: "Poulpe grillé à l'huile d'olive", venue: false },
  { img: 'a-012', tag: 'Spécialité', name: 'Bacalhau à Brás', desc: 'Morue effilochée', venue: false },
  { img: 'a-013', tag: 'Spécialité', name: 'Picanha · Arroz de Marisco · Pastel de Nata', desc: 'Les incontournables à goûter', venue: false },
];

const GUIDE_SUPER = ['a-014a', 'a-014b', 'a-014c', 'a-014d'];

const GUIDE_NOCTURNE = [
  { img: 'a-018', tag: 'Bar à cocktails', name: 'Sal Rosa', desc: 'Cocktails signatures et terrasse', venue: true,
    mapsQuery: 'Sal Rosa Albufeira, Portugal',
    why: "Une terrasse agréable pour commencer la soirée en douceur, avec de bons cocktails et une ambiance décontractée.",
    highlights: ['Cocktails signatures', 'Terrasse agréable en soirée', 'Bonne étape avant le dîner'] },
  { img: 'a-019', tag: 'Bar à cocktails', name: 'Tonic Bar', desc: 'Cocktails artisanaux', venue: true,
    mapsQuery: 'Tonic Bar Albufeira, Portugal',
    why: "Des cocktails soignés dans une ambiance plus intimiste — une bonne option pour démarrer la soirée entre amis ou en couple.",
    highlights: ['Cocktails artisanaux', 'Ambiance cosy', 'Idéal en petit groupe'] },
  { img: 'a-020', tag: 'Bar à cocktails', name: 'Yolo Treehouse', desc: 'Rooftop tropical, ambiance chic', venue: true,
    mapsQuery: 'Yolo Treehouse Albufeira, Portugal',
    why: "Un rooftop à l'ambiance tropicale et soignée, parfait pour admirer le coucher de soleil avant de poursuivre la soirée.",
    highlights: ['Rooftop avec vue', 'Ambiance chic et tropicale', 'Parfait pour le coucher de soleil'] },
  { img: 'a-021', tag: 'Bar animé', name: 'Paulos Bar', desc: 'Musique live', venue: true,
    mapsQuery: 'Paulos Bar Albufeira, Portugal',
    why: "De la musique live et une ambiance animée — une bonne adresse pour une soirée festive dans la vieille ville.",
    highlights: ['Musique live régulière', 'Ambiance animée', 'Au cœur de la vieille ville'] },
  { img: 'a-022', tag: 'Bar animé', name: 'Hot Sun Bar', desc: 'Happy hour et soirées festives', venue: true,
    mapsQuery: 'Hot Sun Bar Albufeira, Portugal',
    why: "Happy hour et ambiance festive : l'endroit où beaucoup de nos hôtes aiment démarrer leur soirée entre amis.",
    highlights: ['Happy hour', 'Ambiance festive', 'Bon plan avant de sortir'] },
  { img: 'a-023', tag: 'Bar animé', name: 'Portas da Villa', desc: 'Bar convivial de la vieille ville', venue: true,
    mapsQuery: 'Portas da Vila Albufeira, Portugal',
    why: "Un bar convivial en plein cœur de la vieille ville, pratique pour un verre avant d'aller danser.",
    highlights: ['Emplacement central', 'Ambiance conviviale', 'Bon point de départ de soirée'] },
  { img: 'a-024', tag: 'Discothèque', name: 'Kiss Disco Club', desc: 'DJ internationaux', venue: true,
    mapsQuery: 'Kiss Disco Club Albufeira, Portugal',
    why: "Une des discothèques les plus connues de la vieille ville, avec une programmation de DJ internationaux.",
    highlights: ['DJ internationaux', 'Grande piste de danse', 'Ouvre tard, ambiance jusqu\'au bout de la nuit'] },
  { img: 'a-025', tag: 'Discothèque', name: 'Club Spaces', desc: 'Musique électronique', venue: true,
    mapsQuery: 'Club Spaces Albufeira, Portugal',
    why: "Pour les amateurs de musique électronique, une salle réputée pour ses soirées jusqu'au bout de la nuit.",
    highlights: ['Musique électronique', 'Ambiance clubbing', 'Plutôt pour les noctambules'] },
  { img: 'a-026', tag: 'Discothèque', name: 'Libertos Club', desc: 'Ambiance festive', venue: true,
    mapsQuery: 'Libertos Club Albufeira, Portugal',
    why: "Une valeur sûre de la vie nocturne locale pour une soirée festive entre amis.",
    highlights: ['Ambiance festive', 'Fréquenté par les groupes d\'amis', 'Musique variée'] },
  { img: 'a-027', tag: 'Discothèque', name: 'Illuzziun Club', desc: 'Tables VIP et DJ sets', venue: true,
    mapsQuery: 'Illuzziun Club Albufeira, Portugal',
    why: "Pour une soirée un peu plus premium, avec tables VIP disponibles et de bons DJ sets.",
    highlights: ['Tables VIP disponibles', 'DJ sets', 'Ambiance plus premium'] },
  { img: 'a-028', tag: 'Vilamoura', name: 'Marina de Vilamoura', desc: 'Promenade parmi les yachts, restaurants et bars lounge', venue: true,
    mapsQuery: 'Marina de Vilamoura, Portugal',
    why: "Une promenade incontournable en soirée : yachts, restaurants et bars lounge, à environ 15 minutes de l'appartement.",
    highlights: ['Promenade au bord de l\'eau', 'Restaurants et bars lounge', 'Ambiance chic, parfait pour un apéro'] },
  { img: 'a-029', tag: 'Casino', name: 'Casino Vilamoura', desc: 'Machines à sous, roulette, blackjack, poker — tenue correcte recommandée', venue: true,
    mapsQuery: 'Casino Vilamoura, Portugal',
    why: "Pour une soirée différente : machines à sous, tables de jeu et parfois des spectacles — tenue correcte recommandée.",
    highlights: ['Roulette, blackjack, poker, machines à sous', 'Tenue correcte recommandée', 'Souvent des spectacles ou concerts'] },
  { img: 'a-030', tag: 'Beach club', name: 'NoSoloÁgua', desc: 'Albufeira', venue: true,
    mapsQuery: 'NoSoloAgua Albufeira, Portugal',
    why: "Un beach club agréable de jour comme de soir, pratique pour prolonger la journée plage en douceur.",
    highlights: ['Ambiance beach club', 'Agréable de jour comme en soirée', 'Proche des plages d\'Albufeira'] },
  { img: 'a-031', tag: 'Beach club', name: 'Purobeach', desc: 'Vilamoura', venue: true,
    mapsQuery: 'Purobeach Vilamoura, Portugal',
    why: "Un beach club plus haut de gamme à Vilamoura, très agréable pour une journée détente qui se prolonge en soirée.",
    highlights: ['Ambiance premium', 'Transats et restauration sur place', 'Belle option pour une journée complète'] },
  { img: 'a-031a', tag: 'Beach club', name: 'Purobeach', desc: 'Vilamoura, vue de nuit', venue: true,
    mapsQuery: 'Purobeach Vilamoura, Portugal',
    why: "Le même Purobeach, mais de nuit : lumières et ambiance lounge pour prolonger la soirée face à la mer.",
    highlights: ['Ambiance lounge en soirée', 'Vue sur mer', 'Belle option après le dîner'] },
  { img: 'a-032', tag: 'Beach club', name: 'Heaven Beach Club', desc: 'Ambiance premium, jour et soir', venue: true,
    mapsQuery: 'Heaven Beach Club Albufeira, Portugal',
    why: "Une ambiance premium toute la journée, qui se prolonge agréablement en soirée — une de nos adresses préférées près des plages.",
    highlights: ['Ambiance premium', 'Agréable de jour comme en soirée', 'Proche des plages d\'Albufeira'] },
];

const GUIDE_VILLES = [
  { img: 'a-033', tag: '38 km · 35-40 min', name: 'Aéroport de Faro', desc: 'Location de voiture fortement recommandée. Taxi 45-60 € · Uber/Bolt 25-40 € · Bus économique mais plus long.', venue: true,
    mapsQuery: 'Aeroporto de Faro, Portugal',
    why: "Votre point d'arrivée en Algarve. Pour la suite du séjour, une voiture de location facilite grandement les déplacements.",
    highlights: ['Location de voiture fortement recommandée', 'Taxi : environ 45-60 €', 'Uber/Bolt : environ 25-40 €'] },
  { img: 'a-034', tag: '3 km · 8-10 min', name: 'Albufeira', desc: 'Vieille ville, marina, plages, excursions en bateau, restaurants et vie nocturne.', venue: true,
    mapsQuery: 'Albufeira, Portugal',
    why: "Le cœur de votre séjour : à quelques minutes de l'appartement, entre vieille ville, marina et plages.",
    highlights: ['Vieille ville pittoresque', 'Marina et excursions en bateau', 'Plages, restaurants et vie nocturne'] },
  { img: 'a-035', tag: '15 km · 20 min', name: 'Vilamoura', desc: 'Marina de luxe, casino, golf, restaurants gastronomiques et bars lounge.', venue: true,
    mapsQuery: 'Vilamoura, Portugal',
    why: "Une ambiance plus chic, à 20 minutes de l'appartement : idéale pour une soirée ou une journée différente.",
    highlights: ['Marina de luxe', 'Casino et golf', 'Restaurants gastronomiques et bars lounge'] },
  { img: 'a-036', tag: '60 km · 50-55 min', name: 'Lagos', desc: 'Ponta da Piedade, plages spectaculaires, grottes, kayak et centre historique.', venue: true,
    mapsQuery: 'Lagos, Algarve, Portugal',
    why: "Une excursion d'une journée qui vaut vraiment le détour : falaises, grottes et plages parmi les plus belles de l'Algarve.",
    highlights: ['Ponta da Piedade et ses falaises', 'Grottes accessibles en kayak ou bateau', 'Centre historique agréable à visiter'] },
  { img: 'a-037', tag: '40 km · 35-40 min', name: 'Portimão', desc: 'Praia da Rocha, promenade maritime, restaurants de fruits de mer et shopping.', venue: true,
    mapsQuery: 'Portimao, Algarve, Portugal',
    why: "Entre plage et vie urbaine : la Praia da Rocha et sa promenade sont idéales pour une journée complète.",
    highlights: ['Praia da Rocha', 'Promenade maritime animée', 'Bons restaurants de fruits de mer'] },
  { img: 'a-038', tag: '30 km · 30 min', name: 'Carvoeiro', desc: "Falaises, Algar Seco, sentiers panoramiques et excursions vers les grottes marines.", venue: true,
    mapsQuery: 'Carvoeiro, Algarve, Portugal',
    why: "Un village de pêcheurs devenu l'une des plus belles adresses de la côte, parfait pour une balade en falaise.",
    highlights: ['Algar Seco et ses formations rocheuses', 'Sentiers panoramiques en bord de falaise', 'Excursions vers les grottes marines'] },
  { img: 'a-039', tag: '25 km · 30 min', name: 'Loulé', desc: 'Marché couvert, château, artisanat et centre historique.', venue: true,
    mapsQuery: 'Loule, Algarve, Portugal',
    why: "Pour une ambiance plus authentique, loin du littoral : marché, artisanat local et ruelles historiques.",
    highlights: ['Marché couvert traditionnel', 'Château et centre historique', 'Bon aperçu de l\'artisanat local'] },
  { img: 'a-040', tag: '65 km · 55 min', name: 'Tavira', desc: 'Pont romain, salines, île de Tavira et ambiance authentique.', venue: true,
    mapsQuery: 'Tavira, Algarve, Portugal',
    why: "Une des villes les plus authentiques de l'Algarve — un peu plus loin, mais qui mérite une journée complète.",
    highlights: ['Pont romain et centre historique', 'Salines et île de Tavira', 'Ambiance plus calme et authentique'] },
  { img: 'a-041', tag: '30 km · 30 min', name: 'Silves', desc: 'Château médiéval, cathédrale et vieille ville.', venue: true,
    mapsQuery: 'Silves, Algarve, Portugal',
    why: "L'ancienne capitale maure de l'Algarve, avec un château médiéval impressionnant qui domine la ville.",
    highlights: ['Château médiéval', 'Cathédrale et vieille ville', 'Belle vue depuis les remparts'] },
];
